name: Test, Lint & Deploy Doover Application

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Push image on failed test or linting (not recommended!)?'
        required: true
        type: boolean

  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    uses: ./.github/workflows/run-linting.yml
    secrets: inherit

  test:
    name: Test Code
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  push_to_registries:
    name: Push Docker Image
    needs: [lint, test]
    if: ${{ needs.test.result == 'success' || (github.event_name == 'workflow_dispatch' &&  github.event.inputs.confirmation == 'true') }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # this is to have permission to pull the base image...
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Doover CLI
        uses: doover/setup-doover@v1

      - name: Deploy Application
        run: doover app deploy
        with:
          DOOVER_API_TOKEN: ${{ secrets.DOOVER_API_TOKEN }}
