name: Run Linting

on:
  workflow_call:


jobs:
  run_tests:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Doover CLI
      uses: spaneng/doover-cli-action@v1
    - name: Run Linting
      run: doover app lint --output-format=github --target-version=py311
      continue-on-error: true
    - name: Check Formatting
      run: doover app format --diff --target-version=py311
      continue-on-error: true
