name: Run Tests

on:
  workflow_dispatch:
  push:

jobs:
  push_to_registries:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: spaneng/doover_device_base
      credentials:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.11

      - name: Run tests
        run: |
          pipenv run pytest --disable-warnings --maxfail=1
