name: Run Tests

on:
  workflow_call:
    secrets:
      DOCKER_PASSWORD:
          required: true

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: spaneng/doover_device_base
      credentials:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Doover CLI
        uses: spaneng/doover-cli-action@v1

      - name: Install the project
        run: |
          apt update && apt install -y git
          uv sync --locked --all-extras --dev

      - name: Run tests
        run: doover app test
