name: Run Tests

on:
  workflow_dispatch:
  push:

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: spaneng/doover_device_base
      credentials:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pipenv and Pipfile packages
        run: |
          apt update && apt install -y git
          pip install pipenv
          pipenv install --dev --ignore-pipfile --deploy --ignore-installed --no-cache-dir        

      - name: Run tests
        run: |
          pipenv run pytest --disable-warnings --maxfail=1
